---
aws_region: us-east-2
application: "{{ application_name}}"
service_name: "{{ application }}"
ecs_cluster: "rome"
log_group_name: "/aws/{{ service_name }}/romedawg"
task_definition_family: "dev-{{ service_name }}"
debug_logs: 0
image_version: latest
role_arn: "arn:aws:iam::701164309191:role/postgres"

postgres_image_repo_credentials:
  secrets: [ ]

postgres_container_definition:
  name: "{{ service_name }}"
  essential: true
  image: "{{ image_repo_uri }}:{{ image_version }}"
  healthCheck:
    command:
      - docker-healthcheck.sh
  environment:
    - name: POSTGRES_HOST
      value: postgres.romedawg.com
    - name: POSTGRES_USERNAME
      value: romedawg
    - name: POSTGRES_DATABASE
      value: romedawg
    - name: POSTGRES_PASSWORD
      value: password
    - name: ADMIN_USER
      value: romedawg
    - name: ADMIN_PASSWORD
      value: password
    - name: METRA_API_USERNAME
      value: f1f57661005181a1238b7d958fdb889f
    - name: METRA_API_PASSWORD
      value: e9152c2ae51643ca236a3521d46d4f39
    - name: SLACK_WEBHOOK
      value: https://hooks.slack.com/services/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
    - name: TWILIO_API_KEY
      value: AC413b62bc99bd258960b97953315b3c46
    - name: TWILIO_API_TOKEN
      value: ac50139f09b054b32f9f4c9dab6e5292
  portMappings:
    - containerPort: 5432
      hostPort: 5432
    - containerPort: 443
      hostPort: 443
    - containerPort: 8080
      hostPort: 8080
  logConfiguration:
    logDriver: awslogs
    options:
      awslogs-group: "{{ log_group_name }}"
      awslogs-region: us-east-2
      awslogs-stream-prefix: "dev-{{ application }}"

# this has been extracted to a variable because it's used also in upgrade/rollback playbooks
postgres_taskdefinition:
  family: "{{ task_definition_family }}"
  launch_type: EC2
  force_create: yes
  network_mode: host
  task_role_arn: "{{ role_arn }}"
  execution_role_arn: "{{ role_arn }}"
  memory: 1024
  containers:
    - "{{ postgres_container_definition | combine(postgres_image_repo_credentials, list_merge='append') }}"
#    - "{{ aws_logger_container_definition }}"  # pulled from ecs_sidecars role
  state: present
